spring:
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://localhost:3306/oreo_book'
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  boot:
    admin:
      client:
        url:
        - http://localhost:8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka